# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{squeezer}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Oldani Pablo"]
  s.date = %q{2011-03-28}
  s.description = %q{an appliaction ready to run}
  s.email = %q{magicche@hotmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/application_controller.rb",
    "app/controllers/blogs_controller.rb",
    "app/controllers/comments_controller.rb",
    "app/controllers/pages_controller.rb",
    "app/controllers/posts_controller.rb",
    "app/controllers/roles_controller.rb",
    "app/controllers/sites_controller.rb",
    "app/controllers/users_controller.rb",
    "app/helpers/squeezer_helper.rb",
    "app/models/ability.rb",
    "app/models/blog.rb",
    "app/models/comment.rb",
    "app/models/page.rb",
    "app/models/permition.rb",
    "app/models/post.rb",
    "app/models/role.rb",
    "app/models/site.rb",
    "app/models/user.rb",
    "app/views/blogs/_entry.haml",
    "app/views/blogs/_form.html.haml",
    "app/views/blogs/edit.html.haml",
    "app/views/blogs/index.html.haml",
    "app/views/blogs/new.html.haml",
    "app/views/blogs/show.html.haml",
    "app/views/comments/_form.html.haml",
    "app/views/comments/_index.html.haml",
    "app/views/comments/_post.html.haml",
    "app/views/comments/edit.haml",
    "app/views/comments/show.js.erb",
    "app/views/layouts/_footer.html.haml",
    "app/views/layouts/_login.haml",
    "app/views/layouts/_menu.html.haml",
    "app/views/layouts/_msn.haml",
    "app/views/layouts/_sidebar.html.haml",
    "app/views/layouts/application.html.erb",
    "app/views/layouts/ice/squeezer/_ice.haml",
    "app/views/layouts/ice/squeezer/ice/_ice.haml",
    "app/views/layouts/ice/squeezer/ice/squeezer/_ice.haml",
    "app/views/layouts/ice/squeezer/ice/squeezer/ice/_ice.haml",
    "app/views/layouts/ice/squeezer/ice/squeezer/ice/squeezer/_ice.haml",
    "app/views/layouts/squeezer/ice/_ice.haml",
    "app/views/layouts/squeezer/ice/squeezer/_ice.haml",
    "app/views/layouts/squeezer/ice/squeezer/ice/_ice.haml",
    "app/views/layouts/squeezer/ice/squeezer/ice/squeezer/_ice.haml",
    "app/views/layouts/squeezer/squeezer.css",
    "app/views/pages/_form.html.haml",
    "app/views/pages/edit.html.haml",
    "app/views/pages/index.html.haml",
    "app/views/pages/new.html.haml",
    "app/views/pages/show.html.haml",
    "app/views/roles/_form.html.haml",
    "app/views/roles/edit.html.haml",
    "app/views/roles/index.html.haml",
    "app/views/roles/new.html.haml",
    "app/views/roles/show.html.haml",
    "app/views/sites/_form.html.haml",
    "app/views/sites/edit.html.haml",
    "app/views/sites/index.html.haml",
    "app/views/sites/new.html.haml",
    "app/views/sites/show.html.haml",
    "app/views/users/index.haml",
    "app/views/users/roles.haml",
    "app/views/users/show.haml",
    "config/routes.rb",
    "lib/generators/squeezer/Gemfile",
    "lib/generators/squeezer/README",
    "lib/generators/squeezer/USAGE",
    "lib/generators/squeezer/squeezer_generator.rb",
    "lib/generators/squeezer/templates/Gemfile",
    "lib/generators/squeezer/templates/app/controllers/application_controller.rb",
    "lib/generators/squeezer/templates/app/controllers/blogs_controller.rb",
    "lib/generators/squeezer/templates/app/controllers/comments_controller.rb",
    "lib/generators/squeezer/templates/app/controllers/forums_controller.rb",
    "lib/generators/squeezer/templates/app/controllers/pages_controller.rb",
    "lib/generators/squeezer/templates/app/controllers/posts_controller.rb",
    "lib/generators/squeezer/templates/app/controllers/roles_controller.rb",
    "lib/generators/squeezer/templates/app/controllers/sites_controller.rb",
    "lib/generators/squeezer/templates/app/controllers/topics_controller.rb",
    "lib/generators/squeezer/templates/app/controllers/users_controller.rb",
    "lib/generators/squeezer/templates/app/helpers/application_helper.rb",
    "lib/generators/squeezer/templates/app/helpers/blogs_helper.rb",
    "lib/generators/squeezer/templates/app/helpers/layout_helper.rb",
    "lib/generators/squeezer/templates/app/helpers/pages_helper.rb",
    "lib/generators/squeezer/templates/app/models/ability.rb",
    "lib/generators/squeezer/templates/app/models/blog.rb",
    "lib/generators/squeezer/templates/app/models/comment.rb",
    "lib/generators/squeezer/templates/app/models/forum.rb",
    "lib/generators/squeezer/templates/app/models/isntall.rb",
    "lib/generators/squeezer/templates/app/models/page.rb",
    "lib/generators/squeezer/templates/app/models/post.rb",
    "lib/generators/squeezer/templates/app/models/role.rb",
    "lib/generators/squeezer/templates/app/models/site.rb",
    "lib/generators/squeezer/templates/app/models/topic.rb",
    "lib/generators/squeezer/templates/app/models/user.rb",
    "lib/generators/squeezer/templates/app/views/blogs/_entry.haml",
    "lib/generators/squeezer/templates/app/views/blogs/_form.html.haml",
    "lib/generators/squeezer/templates/app/views/blogs/edit.html.haml",
    "lib/generators/squeezer/templates/app/views/blogs/index.html.haml",
    "lib/generators/squeezer/templates/app/views/blogs/new.html.haml",
    "lib/generators/squeezer/templates/app/views/blogs/show.html.haml",
    "lib/generators/squeezer/templates/app/views/comments/_form.html.erb",
    "lib/generators/squeezer/templates/app/views/comments/_form.html.haml",
    "lib/generators/squeezer/templates/app/views/comments/_index.html.haml",
    "lib/generators/squeezer/templates/app/views/comments/_post.html.haml",
    "lib/generators/squeezer/templates/app/views/comments/_post2.haml",
    "lib/generators/squeezer/templates/app/views/comments/edit.haml",
    "lib/generators/squeezer/templates/app/views/comments/show.js.erb",
    "lib/generators/squeezer/templates/app/views/confirmations/new.html.erb",
    "lib/generators/squeezer/templates/app/views/devise/confirmations/new.html.erb",
    "lib/generators/squeezer/templates/app/views/devise/mailer/confirmation_instructions.html.erb",
    "lib/generators/squeezer/templates/app/views/devise/mailer/reset_password_instructions.html.erb",
    "lib/generators/squeezer/templates/app/views/devise/mailer/unlock_instructions.html.erb",
    "lib/generators/squeezer/templates/app/views/devise/passwords/edit.html.erb",
    "lib/generators/squeezer/templates/app/views/devise/passwords/new.html.erb",
    "lib/generators/squeezer/templates/app/views/devise/registrations/edit.html.erb",
    "lib/generators/squeezer/templates/app/views/devise/registrations/new.html.erb",
    "lib/generators/squeezer/templates/app/views/devise/sessions/new.html.erb",
    "lib/generators/squeezer/templates/app/views/devise/shared/_links.erb",
    "lib/generators/squeezer/templates/app/views/devise/unlocks/new.html.erb",
    "lib/generators/squeezer/templates/app/views/devise_mailer/confirmation_instructions.html.erb",
    "lib/generators/squeezer/templates/app/views/devise_mailer/reset_password_instructions.html.erb",
    "lib/generators/squeezer/templates/app/views/devise_mailer/unlock_instructions.html.erb",
    "lib/generators/squeezer/templates/app/views/forums/_form.html.haml",
    "lib/generators/squeezer/templates/app/views/forums/edit.html.haml",
    "lib/generators/squeezer/templates/app/views/forums/index.html.haml",
    "lib/generators/squeezer/templates/app/views/forums/new.html.haml",
    "lib/generators/squeezer/templates/app/views/forums/show.html.haml",
    "lib/generators/squeezer/templates/app/views/layouts/_footer.html.haml",
    "lib/generators/squeezer/templates/app/views/layouts/_header.html.haml",
    "lib/generators/squeezer/templates/app/views/layouts/_ice.haml",
    "lib/generators/squeezer/templates/app/views/layouts/_latest.haml",
    "lib/generators/squeezer/templates/app/views/layouts/_login.html.erb",
    "lib/generators/squeezer/templates/app/views/layouts/_login.html.haml",
    "lib/generators/squeezer/templates/app/views/layouts/_menu.html.haml",
    "lib/generators/squeezer/templates/app/views/layouts/_msn.haml",
    "lib/generators/squeezer/templates/app/views/layouts/_sidebar.html.haml",
    "lib/generators/squeezer/templates/app/views/layouts/application.html.erb",
    "lib/generators/squeezer/templates/app/views/layouts/application.html.haml",
    "lib/generators/squeezer/templates/app/views/layouts/ice/squeezer/_ice.haml",
    "lib/generators/squeezer/templates/app/views/pages/_form.html.haml",
    "lib/generators/squeezer/templates/app/views/pages/edit.html.haml",
    "lib/generators/squeezer/templates/app/views/pages/index.html.haml",
    "lib/generators/squeezer/templates/app/views/pages/new.html.haml",
    "lib/generators/squeezer/templates/app/views/pages/show.html.haml",
    "lib/generators/squeezer/templates/app/views/passwords/edit.html.erb",
    "lib/generators/squeezer/templates/app/views/passwords/new.html.erb",
    "lib/generators/squeezer/templates/app/views/registrations/edit.html.erb",
    "lib/generators/squeezer/templates/app/views/registrations/new.html.erb",
    "lib/generators/squeezer/templates/app/views/roles/_form.html.haml",
    "lib/generators/squeezer/templates/app/views/roles/edit.html.haml",
    "lib/generators/squeezer/templates/app/views/roles/index.html.haml",
    "lib/generators/squeezer/templates/app/views/roles/new.html.haml",
    "lib/generators/squeezer/templates/app/views/roles/show.html.haml",
    "lib/generators/squeezer/templates/app/views/roles/user.html.erb",
    "lib/generators/squeezer/templates/app/views/sessions/new.html.erb",
    "lib/generators/squeezer/templates/app/views/shared/_devise_links.erb",
    "lib/generators/squeezer/templates/app/views/sites/_form.html.haml",
    "lib/generators/squeezer/templates/app/views/sites/edit.html.haml",
    "lib/generators/squeezer/templates/app/views/sites/index.html.haml",
    "lib/generators/squeezer/templates/app/views/sites/new.html.haml",
    "lib/generators/squeezer/templates/app/views/sites/show.html.haml",
    "lib/generators/squeezer/templates/app/views/topics/_form.html.haml",
    "lib/generators/squeezer/templates/app/views/topics/edit.html.erb",
    "lib/generators/squeezer/templates/app/views/topics/index.html.haml",
    "lib/generators/squeezer/templates/app/views/topics/new.html.erb",
    "lib/generators/squeezer/templates/app/views/topics/show.html.haml",
    "lib/generators/squeezer/templates/app/views/unlocks/new.html.erb",
    "lib/generators/squeezer/templates/app/views/users/index.haml",
    "lib/generators/squeezer/templates/app/views/users/roles.haml",
    "lib/generators/squeezer/templates/config/devise.rb",
    "lib/generators/squeezer/templates/db/migrate/add_username_user.rb",
    "lib/generators/squeezer/templates/db/migrate/blogs.rb",
    "lib/generators/squeezer/templates/db/migrate/comments.rb",
    "lib/generators/squeezer/templates/db/migrate/create_blogs.rb",
    "lib/generators/squeezer/templates/db/migrate/create_comments.rb",
    "lib/generators/squeezer/templates/db/migrate/create_pages.rb",
    "lib/generators/squeezer/templates/db/migrate/create_permitions.rb",
    "lib/generators/squeezer/templates/db/migrate/create_posts.rb",
    "lib/generators/squeezer/templates/db/migrate/create_roles.rb",
    "lib/generators/squeezer/templates/db/migrate/create_sites.rb",
    "lib/generators/squeezer/templates/db/migrate/data.rb",
    "lib/generators/squeezer/templates/db/migrate/page_data.rb",
    "lib/generators/squeezer/templates/db/migrate/pages.rb",
    "lib/generators/squeezer/templates/db/migrate/posts.rb",
    "lib/generators/squeezer/templates/db/migrate/roles.rb",
    "lib/generators/squeezer/templates/db/migrate/roles_users.rb",
    "lib/generators/squeezer/templates/db/migrate/sites.rb",
    "lib/generators/squeezer/templates/db/migrate/squeez_data.rb",
    "lib/generators/squeezer/templates/doc/clases.png",
    "lib/generators/squeezer/templates/ice/squeezer/ice/_ice.haml",
    "lib/generators/squeezer/templates/ice/squeezer/ice/squeezer/_ice.haml",
    "lib/generators/squeezer/templates/ice/squeezer/ice/squeezer/ice/_ice.haml",
    "lib/generators/squeezer/templates/ice/squeezer/ice/squeezer/ice/squeezer/_ice.haml",
    "lib/generators/squeezer/templates/ice/squeezer/squeezer.css",
    "lib/generators/squeezer/templates/public/javascripts/application.js",
    "lib/generators/squeezer/templates/public/javascripts/jquery-ui.js",
    "lib/generators/squeezer/templates/public/javascripts/jquery-ui.min.js",
    "lib/generators/squeezer/templates/public/javascripts/jquery.cleditor.min.js",
    "lib/generators/squeezer/templates/public/javascripts/jquery.js",
    "lib/generators/squeezer/templates/public/javascripts/jquery.layout.min-1.2.0.js",
    "lib/generators/squeezer/templates/public/javascripts/jquery.min.js",
    "lib/generators/squeezer/templates/public/javascripts/rails.js",
    "lib/generators/squeezer/templates/public/stylesheets/CLEditor1_3_0/images/buttons.gif",
    "lib/generators/squeezer/templates/public/stylesheets/CLEditor1_3_0/images/toolbar.gif",
    "lib/generators/squeezer/templates/public/stylesheets/CLEditor1_3_0/jquery.cleditor.css",
    "lib/generators/squeezer/templates/public/stylesheets/ice/lagota/ice/_ice.haml",
    "lib/generators/squeezer/templates/public/stylesheets/ice/lagota/lagota.css",
    "lib/generators/squeezer/templates/public/stylesheets/ice/squeezer/ice/_ice.haml",
    "lib/generators/squeezer/templates/public/stylesheets/ice/squeezer/ice/squeezer/_ice.haml",
    "lib/generators/squeezer/templates/public/stylesheets/ice/squeezer/ice/squeezer/ice/_ice.haml",
    "lib/generators/squeezer/templates/public/stylesheets/ice/squeezer/ice/squeezer/ice/squeezer/_ice.haml",
    "lib/generators/squeezer/templates/public/stylesheets/ice/squeezer/squeezer.css",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-bg_diagonals-thick_18_b81900_40x40.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-bg_diagonals-thick_20_666666_40x40.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-bg_flat_10_000000_40x100.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-bg_glass_100_f6f6f6_1x400.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-bg_glass_100_fdf5ce_1x400.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-bg_glass_65_ffffff_1x400.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-bg_gloss-wave_35_f6a828_500x100.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-bg_highlight-soft_100_eeeeee_1x100.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-bg_highlight-soft_75_ffe45c_1x100.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-icons_222222_256x240.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-icons_228ef1_256x240.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-icons_ef8c08_256x240.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-icons_ffd27a_256x240.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/images/ui-icons_ffffff_256x240.png",
    "lib/generators/squeezer/templates/public/stylesheets/ui-lightness/jquery-ui-1.8.5.custom.css",
    "lib/squeezer.rb",
    "squeezer.gemspec",
    "test/helper.rb",
    "test/test_squeezer.rb"
  ]
  s.homepage = %q{http://github.com/olvap/squeezer}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{i have to learn the meaning of summary}
  s.test_files = [
    "test/helper.rb",
    "test/test_squeezer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_development_dependency(%q<haml>, [">= 0"])
      s.add_development_dependency(%q<devise>, ["~> 1.1.rc2"])
      s.add_development_dependency(%q<paperclip>, [">= 0"])
      s.add_development_dependency(%q<cancan>, [">= 0"])
      s.add_development_dependency(%q<nifty-generators>, [">= 0"])
      s.add_development_dependency(%q<jquery-rails>, [">= 0"])
      s.add_development_dependency(%q<inherited_resources>, [">= 0"])
      s.add_development_dependency(%q<mysql>, [">= 0"])
      s.add_development_dependency(%q<meta_search>, [">= 0"])
      s.add_development_dependency(%q<rails_helpers_fix>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<devise>, ["~> 1.1.rc2"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<cancan>, [">= 0"])
      s.add_dependency(%q<nifty-generators>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<inherited_resources>, [">= 0"])
      s.add_dependency(%q<mysql>, [">= 0"])
      s.add_dependency(%q<meta_search>, [">= 0"])
      s.add_dependency(%q<rails_helpers_fix>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<devise>, ["~> 1.1.rc2"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<cancan>, [">= 0"])
    s.add_dependency(%q<nifty-generators>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<inherited_resources>, [">= 0"])
    s.add_dependency(%q<mysql>, [">= 0"])
    s.add_dependency(%q<meta_search>, [">= 0"])
    s.add_dependency(%q<rails_helpers_fix>, [">= 0"])
  end
end

